% This script claculates the pairwise linear correlation coefficient
% between each pair of ROIs for each subject separately.
% The list of subjects is generated by 'allsub_all.m'.
% Path variables below should be set properly.

clear all

%% Basic settings (including path variables)

basename = 'sald';
rootpath = 'c:\projects\transfer_learning\roiwise_data\';     % Path to preprocessed data.
outpath =  'c:\projects\transfer_learning\correlation_maps\'; % Path to correlation data.
run('allsub_all.m')
numROI=111;

%% Calculating pairwise linear correlation coefficients

allsub_corr = zeros(numROI, numROI, length(subnames));
for subject = 1:length(subnames)
    subname = subnames{subject};
    
    disp(sprintf('%s',subname));
    load([rootpath subname 'resting_roiwise.mat'])
    CORR = corr(roiY);
    allsub_corr(:, :, subject) = CORR;
end
save([outpath 'resting_harvardoxfordfull_' num2str(numROI) 'ROIs.mat'], 'allsub_corr')